### ISSUE TITLE
Simple issue probably, but I cannot go around it

### ISSUE THREAD

**Issue by kohasz** [trishmapow/obd-gui#1]
Hi.

I'm using a rasp pi 4 without the camera or relay board. 
This is a fresh install of raspbian with everything updated and I've followed your instructions to the dot.
I manage to connect to the bluetooth, but when I try to run gui.py I get this error:

```
pi@raspberrypi:~/obd-gui $ sudo python3 gui.py
Traceback (most recent call last):
  File "gui.py", line 135, in <module>
    main()
  File "gui.py", line 56, in main
    conn = connect(watchlist=list(itertools.chain.from_iterable(watchlist), debug=DEBUG_CONNECT))
TypeError: list() takes no keyword arguments
```

any ideas on what should I do? 
what am I missing?

thanks for the work on this, awesome tool!

**Comment by kohasz** [comment]
changing that line to:

`conn = connect(watchlist=list(itertools.chain.from_iterable(watchlist)), debug=DEBUG_CONNECT)`

fixed the issue.

**Comment by trishmapow** [comment]
Thanks for noticing the typo! Haven't used this in a while, glad to see it's useful for someone else.

**Comment by kohasz** [comment]
thanks for sharing this, will help me a lot in the near future with my project!
