### ISSUE TITLE
Great inspiration!

### ISSUE THREAD

**Issue by Cushychicken** [trishmapow/obd-gui#3]
Wanted to leave this on twitter or somewhere else but I couldn't find you on twitter. 

This is a _super_ helpful starting point for me on some CAN sniffer stuff I'm doing that I want to integrate a GUI frontend into. Just wanted to drop you a note to say thanks for posting this and I found it super helpful.

**Comment by Cushychicken** [comment]
(Please feel free to close this issue once you see it - I just opened it because it was the most direct way to give you some positive feedback about your work. 👍 )

**Comment by trishmapow** [comment]
You're welcome! Almost forgot about this project haha, glad it was useful in some way.
